<div class="row"><div class="col-md-12"><div class="panel panel-success"><div class="panel-heading "><h3 class="panel-title">HTML Table Preview</h3></div>
<table border=1 class="table table-striped table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">survived</th>
<th title="Field #2">pclass</th>
<th title="Field #3">name</th>
<th title="Field #4">sex</th>
<th title="Field #5">age</th>
<th title="Field #6">sibsp</th>
<th title="Field #7">parch</th>
<th title="Field #8">ticket</th>
<th title="Field #9">fare</th>
<th title="Field #10">cabin</th>
<th title="Field #11">embarked</th>
</tr></thead>
<tbody><tr><td>0</td>
<td align="right">3</td>
<td>Braund, Mr. Owen Harris</td>
<td>male</td>
<td align="right">22</td>
<td>1</td>
<td>0</td>
<td>A/5 21171</td>
<td align="right">7.2500</td>
<td> </td>
<td>S</td>
</tr>
<tr><td>1</td>
<td align="right">1</td>
<td>Cumings, Mrs. John Bradley (Florence Briggs Thayer)</td>
<td>female</td>
<td align="right">38</td>
<td>1</td>
<td>0</td>
<td>PC 17599</td>
<td align="right">71.2833</td>
<td>C85</td>
<td>C</td>
</tr>
<tr><td>1</td>
<td align="right">3</td>
<td>Heikkinen, Miss. Laina</td>
<td>female</td>
<td align="right">26</td>
<td>0</td>
<td>0</td>
<td>STON/O2. 3101282</td>
<td align="right">7.9250</td>
<td> </td>
<td>S</td>
</tr>
<tr><td>1</td>
<td align="right">1</td>
<td>Futrelle, Mrs. Jacques Heath (Lily May Peel)</td>
<td>female</td>
<td align="right">35</td>
<td>1</td>
<td>0</td>
<td>113803</td>
<td align="right">53.1000</td>
<td>C123</td>
<td>S</td>
</tr>
<tr><td>0</td>
<td align="right">3</td>
<td>Allen, Mr. William Henry</td>
<td>male</td>
<td align="right">35</td>
<td>0</td>
<td>0</td>
<td>373450</td>
<td align="right">8.0500</td>
<td> </td>
<td>S</td>
</tr>
</tbody></table>
</div></div></div>

survival -	Survival = 0 = No, 1 = Yes

pclass -    Ticket class = 1 = 1st, 2 = 2nd, 3 = 3rd

sex -	        Sex	

Age	-       Age in years	

sibsp -	    # of siblings / spouses aboard the Titanic	

parch -	    # of parents / children aboard the Titanic	

ticket -    Ticket number	

fare -    Passenger fare	

cabin -	    Cabin number	

embarked -	Port of Embarkation	C = Cherbourg, Q = Queenstown, S = Southampton
------------------------------------------------------------------------------------------------
pclass: A proxy for socio-economic status (SES)
1st = Upper
2nd = Middle
3rd = Lower

age: Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5

sibsp: The dataset defines family relations in this way...
Sibling = brother, sister, stepbrother, stepsister
Spouse = husband, wife (mistresses and fianc√©s were ignored)

parch: The dataset defines family relations in this way...
Parent = mother, father
Child = daughter, son, stepdaughter, stepson
Some children travelled only with a nanny, therefore parch=0 for them.